SmartHome/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SmartHome.Controllers
{
    public class ContactController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
    }
}

SmartHome/Controllers/DeviceController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SmartHome.Models;
using SmartHome.ViewModels;

namespace SmartHome.Controllers
{
    public class DeviceController : Controller
    {
        private readonly IDeviceRepository _deviceRepository;
        private readonly ISectionRepository _sectionRepository;

        public DeviceController(IDeviceRepository deviceRepository, ISectionRepository sectionRepository)
        {
            _deviceRepository = deviceRepository;
            _sectionRepository = sectionRepository;
        }

        public ViewResult List(string section)
        {
            IEnumerable<Device> devices;
            string currentSection;

            if (string.IsNullOrEmpty(section))
            {
                devices = _deviceRepository.AllDevices.OrderBy(d => d.DeviceId);
                currentSection = "All devices";
            }
            else
            {
                devices = _deviceRepository.AllDevices.Where(d => d.Section.SectionName == section).OrderBy(d => d.DeviceId);
                currentSection = _sectionRepository.AllSections.FirstOrDefault(s => s.SectionName == section)?.SectionName;
            }



            return View(new DevicesListViewModel
            {
                Devices = devices,
                CurrentSection = currentSection
            });
        }
        public IActionResult Details(int id)
        {
            var device = _deviceRepository.GetDeviceId(id);
            if (device == null)
                return NotFound();

            return View(device);
        }
        public IActionResult Index()
        {
            return View(); 
        }
    }
}

SmartHome/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/images/IOT.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/images/Home.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/images/Smart.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

SmartHome/Views/Shared/_DeviceCard.cshtml
@model Device

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Url.Content(@Model.ImageThumbnailUrl)" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.DeviceId.ToString("c")</h3>
            <h3>
                <a asp-controller="Device" asp-action="Details" asp-route-id="@Model.DeviceId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-deviceId="@Model.DeviceId">Add to cart</a>
            </p>
        </div>
    </div>
</div>

SmartHome/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap_3_3_7/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        @await Component.InvokeAsync("SectionMenu")
                    <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                        @await Component.InvokeAsync("ShoppingCartSummary")
                        <partial name="_LoginPartial"/>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" alt="Smart Home'" src="~/images/Smart-Home-Logo.png" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
    @RenderSection("Scripts", required:false)
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap_3_3_7/js/bootstrap.js"></script>
</body>
</html>